version: '3'

services:
  mongo_db:
    image: mongo
    container_name: mongoDB
    restart: always
    ports:
      - 27017:27017
  app:
    build: .
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    depends_on:
      - mongo_db